### ISSUE TITLE
I can't run the program.

### ISSUE THREAD

**Issue by TheLizzard** [benjcollins/language#1]
This is what I get when I try running the program:
```
C:\Users\TheLizzard\language-master>go run main.go
main.go:4:2: cannot find package "compiler/backend" in any of:
        c:\go\src\compiler\backend (from $GOROOT)
        C:\Users\TheLizzard\go\src\compiler\backend (from $GOPATH)
main.go:5:2: cannot find package "compiler/frontend" in any of:
        c:\go\src\compiler\frontend (from $GOROOT)
        C:\Users\TheLizzard\go\src\compiler\frontend (from $GOPATH)
main.go:6:2: cannot find package "compiler/syntax" in any of:
        c:\go\src\compiler\syntax (from $GOROOT)
        C:\Users\TheLizzard\go\src\compiler\syntax (from $GOPATH)
```
From the error I understand that go is trying to import the files from `%GOPATH%` (which is set to `C:\Users\TheLizzard\go`) or from the actual folder of installation (which is `C:\go`).

**Comment by benjcollins** [comment]
I think if you put the files in go/src/compiler it should work. The other thing could be if you are using the command go run on windows it doesn't work very well you should use go build instead and just run the executable.

**Comment by TheLizzard** [comment]
Still doesn't work I will try on Ubuntu 20 later.

**Comment by benjcollins** [comment]
Yeah that's probably best i have been developing it on Ubuntu using WSL.

**Comment by TheLizzard** [comment]
It still doesn't work :(
![image](https://user-images.githubusercontent.com/64270863/93198419-e9c41500-f744-11ea-8f02-928678a2770e.png)
On my computer `$GOPATH=""`

**Comment by TheLizzard** [comment]
Well for some reason I misspelled `"src"` as `"scr"` which is the reason that it doesn't run :D

**Comment by TheLizzard** [comment]
Now it works :-)
